# User config
author: "hy-zhao22"
tagline: "hy-zhao22 Certfied Jekyll Theme"
description: "Intellectual Calculation Projects."
keywords: "Deep-learning, Intelligent calculation"
email: "hy-zhao22@mails.tsinghua.edu.cn"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed

gitalk:
  client_id: 'a669aa04c262002c5535'
  client_secret: '3e5b1092b529ea90c7d6b81c4b73be6cc6216248'
  owner: 'THIRTY-EIGHT-ZHY'
  repo: 'blog-comments'
  admin: ['THIRTY-EIGHT-ZHY']
  id: location.pathname
  language: 'zh-CN'
  distractionFreeMode: false